import random

# List of quotes
quotes = [
    "Keep pushing forward! - Gowtham",
    "Success is the sum of small efforts, repeated daily.",
    "Code, Learn, Improve, Repeat!",
    "Your only limit is your mind.",
    "The best way to predict the future is to create it.",
    "Believe in yourself and all that you are.",
    "Dream big and dare to fail.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Stay focused, go after your dreams, and keep moving toward your goals.",
    "Great things never come from comfort zones.",
    "Opportunities don't happen. You create them.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t let yesterday take up too much of today.",
    "Your limitation—it’s only your imagination.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Do what you can with all you have, wherever you are.",
    "The road to success and the road to failure are almost exactly the same.",
    "Doubt kills more dreams than failure ever will.",
    "Whether you think you can or you think you can’t, you’re right.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "Push yourself, because no one else is going to do it for you.",
    "Your mindset determines your future.",
    "Dream it. Wish it. Do it.",
    "You didn’t come this far to only come this far.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Work until your idols become your rivals.",
    "Dream big. Start small. Act now.",
    "Every day is a chance to get better.",
    "Nothing worth having comes easy.",
    "If it doesn’t challenge you, it won’t change you.",
    "What comes easy won’t last. What lasts won’t come easy.",
    "Work hard in silence, let success make the noise.",
    "There is no substitute for hard work.",
    "Learning never exhausts the mind.",
    "Stay curious. Keep learning. Keep growing.",
    "Programming isn’t about what you know; it’s about what you can figure out.",
    "A bug is just an opportunity to learn.",
    "Fail fast, fix faster.",
    "Talk is cheap. Show me the code. — Linus Torvalds",
    "It’s not a bug. It’s an undocumented feature.",
    "Stay hungry. Stay foolish. — Steve Jobs",
    "You miss 100% of the shots you don’t take. — Wayne Gretzky",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
    "Strive not to be a success, but rather to be of value.",
    "Surround yourself with people who are going to lift you higher.",
    "You don’t have to be great to start, but you have to start to be great.",
    "A goal without a plan is just a wish.",
    "Tough times don’t last. Tough people do.",
    "Every accomplishment starts with the decision to try.",
    "Don’t be afraid to fail. Be afraid not to try.",
    "Courage is resistance to fear, mastery of fear—not absence of fear.",
    "Take time to do what makes your soul happy.",
    "You owe yourself the love that you so freely give to others.",
    "A happy mind leads to a happy life.",
    "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
    "Creativity takes courage. — Henri Matisse",
    "Do what you love, and you’ll never work a day in your life.",
    "Creativity is intelligence having fun. — Albert Einstein",
    "Everything you can imagine is real.",
    "Make today so awesome that yesterday gets jealous.",
    "Don’t wait. The time will never be just right.",
    "You are stronger than you think.",
    "If you can dream it, you can do it.",
    "Stay positive, work hard, and make it happen.",
    "The best investment you can make is in yourself."
]

def get_quote():
    """Returns a random quote."""
    return random.choice(quotes)

# Example usage
print(get_quote())
